# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c0a5dd51c8c24762eed11fb2af4f431dd26bb73c3a815dd8b1a425a06610cc2374dc88d54e256226137b45030d78dce846dfd2b233a37b1bbe3396e19360b4

test:
  secret_key_base: 605c6b020405237afa3899a094fe48943d0d221a7a9b3a6f7e7117553c8107f24f9a1e36ea7cbf977836e31ea7fed4cf4047c5a4e7209d97368a66aa19606cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
